apiVersion: v1
kind: Pod
metadata:
  name: geth-temp
spec:
  containers:
    - name: geth-temp
      image: ubuntu
      volumeMounts:
        - mountPath: '/geth-volume'
          name: geth-volume
  volumes:
    - name: geth-volume
      persistentVolumeClaim:
        claimName: geth-volume-claim
