apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: geth-mainnet-pvc
spec:
  storageClassName: ssd-retain-sc
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  resources:
    requests:
      storage: 1000G
